apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 192.168.88.1
      peer-asn: 65530
      my-asn: 64500
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 192.168.100.0/24
      avoid-buggy-ips: true

# apiVersion: metallb.io/v1beta1
# kind: BGPPeer
# metadata:
#   name: peer-sample1
#   namespace: metallb-system
# spec:
#   peerAddress: 192.168.99.1
#   peerASN: 65000
#   myASN: 64500
#   routerID: 192.168.100.10
#   peerPort: 1
#   holdTime: "180s"
#   keepaliveTime: "180s"
#   sourceAddress: "1.1.1.1"
#   password: "test"
#   nodeSelectors:
#   - matchExpressions:
#     - key: kubernetes.io/hostname
#       operator: In
#       values: [hostA, hostB]